### ISSUE TITLE
Issue about RFlink-ESP

### ISSUE THREAD

**Issue by schmurtzm** [burlizzi/burlizzi.github.io#1]
Hi,

Sorry it's not an issue about this project but it was the only way I found to contact you 😅 
I saw recently a PR from you on the RFlink-ESP project. 
I was thinking that the alexa protocol that you have created and other improvements could be interesting but I don't find your fork anymore. 
Do you think that you could you share it again please ?

Thank you.
Best regards.

**Comment by burlizzi** [comment]
Sure,
I had to delete the fork because I forgot to remove my private password in
the code, even if I changed it it would be in the history.
I will fork again and share the code but not the password ;)
It's late now in Europe, will do it tomorrow.

Il Lun 22 Mar 2021, 23:29 Schmurtz ***@***.***> ha scritto:

**Comment by burlizzi** [comment]
the code is there, take it "as is"

**Comment by burlizzi** [comment]
cleanup
